### PR TITLE
Remove getFields method

### LINKED ISSUE #27: Remove getFields from Reader
Where is it used exactly? Because I can't find any usage.

AFAIK it was used with the "old" Converter structure, but it isn't used now.

So can we just get rid of it? I think it causes a lot of trouble, especially with readers using an underlying iterator.

If we are going to have Item objects discussed in #14 it can directly be added to Item objects.

### PR DESCRIPTION
**Pull request by sagikazarmark**
Fix #27

### CODE REVIEW

**Comment by sagikazarmark** [comment]
@ddeboer are you OK with this as well? I would wait for some other changes in the repo prior to merging this as some classes will be removed anyway, why bother those then?

**Comment by ddeboer** [comment]
Yes, agreed on removing the method and keeping this PR on hold for now.

**Comment by ddeboer** [comment]
Now conflicts with master. Could you please rebase?

**Comment by ddeboer** [comment]
Rebased on master.

**Pull request merged**
