### PR TITLE
Update documentation for portphp/spreadsheet

### LINKED ISSUE #90: Update documentation for portphp/spreadsheet
Adding a reminder here before I forget.

All of the docs are here if I'm not mistaken https://github.com/portphp/portphp/tree/master/docs

### PR DESCRIPTION
**Pull request by infomaniac50**
The new library is mostly a dropin replacement for the old one. I simply replaced all of the instances of excel with spreadsheet.

- portphp/excel becomes portphp/spreadsheet
- Excel* becomes Spreadsheet*

This fixes #90

### CODE REVIEW

**Comment by Baachi** [comment]
I'm not a big fan of replace the documentation. The portphp/excel library is still available for users they didn't migrate to portphp/spreadsheet yet.

So i would rather take a not in the portphp/excel documentation, that this library is not maintained anymore and suggest the users to migrate spreadsheet.

**Comment by infomaniac50** [comment]
I combined the new and old documentation. I did not add any deprecation notices. I'll let you do that when you are ready.

**Comment by infomaniac50** [comment]
What's this business about analysis errors in Scrutinizer? Is that something on their end?

**Comment by Baachi** [comment]
I would say, there is something wrong on there end. I'll merge them regardless of the error, because no code has been touched.

Thank you very much @infomaniac50 for your effort!

**Pull request merged**
